name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Date
        id: get_date
        run: |
          echo "YEAR=$(date +%Y)" >> $GITHUB_OUTPUT
          echo "WEEK_NUMBER=$(date +%V)" >> $GITHUB_OUTPUT
          echo "MONTH_NUMBER=$(date +%m)" >> $GITHUB_OUTPUT

      - name: Count Releases This Month
        id: count_releases
        uses: actions/github-script@v6
        with:
          script: |
            const { repo } = context.repo;
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const thisMonthReleases = releases.data.filter(release => {
              const createdAt = new Date(release.created_at);
              return createdAt.getMonth() + 1 === parseInt('${{ steps.get_date.outputs.MONTH_NUMBER }}') &&
                     createdAt.getFullYear() === parseInt('${{ steps.get_date.outputs.YEAR }}');
            });
            return thisMonthReleases.length;

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_date.outputs.YEAR }}.${{ steps.get_date.outputs.MONTH_NUMBER }}.${{ steps.count_releases.outputs.result }}
          release_name: REPOSITORY_NAME ${{ steps.get_date.outputs.YEAR }} - W${{ steps.get_date.outputs.WEEK_NUMBER }}
          body: |
            Automatically generated release notes for ${{ github.event.repository.name }} ${{ steps.get_date.outputs.YEAR }} - W${{ steps.get_date.outputs.WEEK_NUMBER }}.
          draft: false
          prerelease: false
